#!/bin/sh
# If you are looking to change accessibility profile settings, plesae look in
# bin/casper-a11y-enable.

. /usr/share/debconf/confmodule
. /etc/casper.conf

PREREQ=""
DESCRIPTION="Configuring accessibility options..."
db_get passwd/username
TARGET_USERNAME="$RET"

for x in $(cat /proc/cmdline); do
	case $x in
		# Lesser Visual Impairment
		access=v1)
			/usr/bin/casper-a11y-enable -login -user="$TARGET_USERNAME" -chroot=/target -debug high-contrast
                        ;;
		# Moderate Visual Impairment
		access=v2)
			/usr/bin/casper-a11y-enable -login -user="$TARGET_USERNAME" -chroot=/target -debug magnifier
                        ;;
		# Blindness
		access=v3)
			/usr/bin/casper-a11y-enable -login -user="$TARGET_USERNAME" -chroot=/target -debug blindness
                        ;;
		# Braille
		braille=ask)
			/usr/bin/casper-a11y-enable -login -user="$TARGET_USERNAME" -chroot=/target -debug braille
                        ;;
		# Minor Motor Difficulties
		access=m1)
			/usr/bin/casper-a11y-enable -login -user="$TARGET_USERNAME" -chroot=/target -debug keyboard-modifiers
                        ;;
		# Motor Difficulties - pointing devices
		access=m2)
			/usr/bin/casper-a11y-enable -login -user="$TARGET_USERNAME" -chroot=/target -debug onscreen-keyboard
                        ;;
		esac
done
