#!/bin/sh -e

# copy cached wallpaper for ureadahead taking it into account
# if $HOME already existed before, discard: next reboot will
# generate the right cached wallpaper. Just missing ureadahead
# optimization

. /usr/share/debconf/confmodule
db_get passwd/username
TARGET_USERNAME="$RET"
LIVE_USER="ubuntu"

if [ -d /home/$LIVE_USER/.cache/wallpaper ] && [ ! -d /target/home/$TARGET_USERNAME/.cache/wallpaper ]; then
	mkdir -p /target/home/$TARGET_USERNAME/.cache
	cp -rp /home/$LIVE_USER/.cache/wallpaper /target/home/$TARGET_USERNAME/.cache
	chroot /target chown -R $TARGET_USERNAME.$TARGET_USERNAME /home/$TARGET_USERNAME/.cache
fi
