#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

USERNAME="ubuntu"

chroot /root /usr/sbin/adduser --gecos "" --disabled-password  "$USERNAME"
chroot /root /usr/sbin/adduser --group --system admin
chroot /root /usr/sbin/adduser "$USERNAME" admin
chroot /root /usr/sbin/adduser "$USERNAME" plugdev
chroot /root /usr/sbin/adduser "$USERNAME" audio
chroot /root /usr/sbin/adduser "$USERNAME" video
chroot /root /usr/sbin/adduser "$USERNAME" scanner

if [ -f /root/etc/sudoers ]; then
    grep -q '^%admin' /root/etc/sudoers && sed -i -e '/^%admin/s/ALL$/NOPASSWD: ALL/' /root/etc/sudoers || echo '%admin  ALL=(ALL) NOPASSWD: ALL' >> /root/etc/sudoers
fi

# XXX - awful hack to stop xscreensaver locking the screen (#7150)
echo 'RUNNING_UNDER_GDM="yes"' >> /root/etc/environment

exit 0
