#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

chroot /root debconf-communicate -fnoninteractive > /dev/null <<EOF
set passwd/root-password-crypted *
set passwd/user-password-crypted *
set passwd/user-fullname Ubuntu LiveCD user
set passwd/username ubuntu
set passwd/user-uid 999
EOF

chroot /root /usr/lib/user-setup/user-setup-apply

if [ -f /root/etc/sudoers ]; then
    grep -q '^%admin' /root/etc/sudoers && sed -i -e '/^%admin/s/ALL$/NOPASSWD: ALL/' /root/etc/sudoers || echo '%admin  ALL=(ALL) NOPASSWD: ALL' >> /root/etc/sudoers
fi

# XXX - awful hack to stop xscreensaver locking the screen (#7150)
echo 'RUNNING_UNDER_GDM="yes"' >> /root/etc/environment

exit 0
