#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

ROOTDEV=/dev/cloop0
FSTAB=/root/etc/fstab

cat > $FSTAB <<EOF
$ROOTDEV / auto noatime 0 0
tmpfs /tmp tmpfs nosuid,nodev 0 0
EOF

exit 0
