#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login"

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

username="ubuntu"

if [ -f /root/etc/gdm/gdm-cdd.conf ]; then
    GDMCONF=/root/etc/gdm/gdm-cdd.conf
else
    GDMCONF=/root/etc/gdm/gdm.conf
fi

if [ -f ${GDMCONF} ]; then
    # Configure GDM autologin
    sed -i \
        -e "s/^AutomaticLoginEnable=.*\$/AutomaticLoginEnable=true/" \
        -e "s/^AutomaticLogin=.*\$/AutomaticLogin=$username/" \
        -e "s/^TimedLoginEnable=.*\$/TimedLoginEnable=true/" \
        -e "s/^TimedLogin=.*\$/TimedLogin=$username/" \
        -e "s/^TimedLoginDelay=.*\$/TimedLoginDelay=10/" \
        ${GDMCONF}
fi

if [ -f /root/etc/kde3/kdm/kdmrc ]; then
    # Configure KDM autologin
    sed -i -r \
        -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
        -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$username/" \
        -e "s/^#?AutoReLogin=.*\$/AutoReLogin=true/" \
        /root/etc/kde3/kdm/kdmrc
fi

if chroot /root /usr/bin/which kpersonalizer >/dev/null; then
    # Disable first-login wizard for KDE
    if [ ! -f /root/etc/kde3/kpersonalizerrc ]; then
        cat > /root/etc/kde3/kpersonalizerrc <<EOF
[General]
FirstLogin=false
EOF
    else
        echo "I'm not smart enough to disable kpersonalizer startup" >&2
        echo "Because kpersonalizerrc already exists" >&2
    fi
fi

log_end_msg
