#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up keyboard"

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

kbd=us

for x in $(cat /proc/cmdline); do
                case $x in
                        kbd-chooser/method=*)
                                kbd=${x#kbd-chooser/method=}
                                ;;
                esac
done

chroot /root /usr/sbin/install-keymap $kbd
chroot /root debconf-communicate -fnoninteractive > /dev/null <<EOF
register debian-installer/dummy debian-installer/keymap
set debian-installer/keymap $kbd
EOF
log_end_msg
