#! /bin/sh

PREREQ=""
DESCRIPTION="Loading preseed file..."

. /scripts/functions

prereqs ()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

log_begin_msg "$DESCRIPTION"

location=
for x in $(cat /proc/cmdline); do
	case $x in
		preseed/file=*)
			location="${x#preseed/file=}"
			;;
	esac
done

if [ "$location" ]; then
	chroot /root debconf-set-selections < "$location"
fi

log_end_msg

exit 0
