#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring accessibility options"

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"
log_end_msg
