#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling update-notifier"

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

rm /root/etc/xdf/autostart/update-notifier.desktop

log_end_msg
