#!/bin/sh

set -e

. /usr/share/debconf/confmodule

log() {
    logger -t casper "$@"
}

log "Loading modules..."
modprobe cloop
modprobe loop
modprobe ext2 || true
modprobe dm-mod

first=0
while ! [ /dev/cloop0 -a -c /dev/mapper/control ]; do
    if [ $first -eq 0 ]; then
        log "Waiting for udev to catch up..."
        first=1
    fi
    sleep 1
done

exit 0
