#!/bin/sh

if [ "$TERM_TYPE" = "serial" ]; then
    # Don't bother trying to configure or start X on a serial console
    rm -f /etc/rc?.d/S??[gxk]dm
    exit 0
fi

. /usr/share/debconf/confmodule

db_register debian-installer/dummy xserver-xorg/autodetect_keyboard || true
db_set xserver-xorg/autodetect_keyboard true || true
db_fset xserver-xorg/autodetect_keyboard seen true || true

db_x_save

debconf-copydb -p '^(debian-installer/keymap|xserver-xorg/autodetect_keyboard)$' configdb target_configdb

#casper-reconfigure -fpassthrough xserver-xorg
