#! /bin/sh -e

. /usr/share/debconf/confmodule

db_get casper/enable
if [ "$RET" = true ]; then
    # Pull in the rest of casper
    anna-install casper-udeb

    # Disable installation of many Priority >= standard udebs.
    db_set anna/standard_modules false || true

    # Be less interactive about network configuration
    db_register debian-installer/dummy netcfg/choose_interface
    db_fset netcfg/choose_interface seen true

    db_register debian-installer/dummy netcfg/dhcp_failed
    db_fset netcfg/dhcp_failed seen true

    db_register debian-installer/dummy netcfg/dhcp_options
    db_fset netcfg/dhcp_options seen true
    db_set netcfg/dhcp_options 'Do not configure the network at this time'

    db_register debian-installer/dummy netcfg/get_hostname
    db_set netcfg/get_hostname ubuntu
    db_fset netcfg/get_hostname seen true

    db_register debian-installer/dummy netcfg/no_interfaces
    db_fset netcfg/no_interfaces seen true

    db_register debian-installer/dummy netcfg/wireless_wep
    db_fset netcfg/wireless_wep seen true

    db_register debian-installer/dummy netcfg/wireless_essid
    db_fset netcfg/wireless_essid seen true

    db_register debian-installer/dummy netcfg/wireless_essid_again
    db_fset netcfg/wireless_essid_again seen true
fi
