#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

casper-md5check /cdrom /cdrom/md5sum.txt < /dev/tty1 > /dev/tty1
