#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring gnome-panel-data..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

panel_version=$(chroot /root /usr/bin/dpkg-query -W --showformat='${Version}' gnome-panel-data 2>/dev/null) || panel_version=""
if [ -n "$panel_version" ]; then
    printf "[org.gnome.desktop.lockdown]\ndisable-lock-screen=true\n" >> /root/usr/share/glib-2.0/schemas/casper.gschema.override
    chroot /root glib-compile-schemas /usr/share/glib-2.0/schemas/
fi

log_end_msg
