#! /bin/sh

PREREQ=""
DESCRIPTION="Loading preseed file..."

. /scripts/casper-functions

prereqs ()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

log_begin_msg "$DESCRIPTION"

location=
for x in $(cat /proc/cmdline); do
	case $x in
		preseed/file=*)
			location="${x#preseed/file=}"
			;;
		file=*)
			location="${x#file=}"
			;;
		url=*)
			location="${x#url=}"
			mount -n -o bind /sys /root/sys
			mount -n -o bind /proc /root/proc
			mount -n -o bind /dev /root/dev
			mkdir -p /root/var/run/network
			chroot /root ifup -a
			chroot /root wget -P /tmp "$location"
			chroot /root ifdown -a
			umount /root/sys
			umount /root/proc
			umount /root/dev
			location="/tmp/$(basename "$location")"
			;;
		*/*=*)
			question="${x%%=*}"
			value="${x#*=}"
			casper-preseed /root "$question" "$value"
			;;
		locale=*)
			value="${x#*=}"
			casper-preseed /root debian-installer/locale "$value"
			;;
	esac
done

if [ "$location" ]; then
	chroot /root debconf-set-selections < "/root$location"
fi

log_end_msg

exit 0
