#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling restricted-manager..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

rm -f /root/etc/xdg/autostart/restricted-manager.desktop

rm -f /root/etc/xdg/autostart/restricted-manager-kde.desktop

# Since we disable restricted-manager, there isn't much point generating the
# fglrx or nvidia modules either. The other restricted modules may still be
# useful.
sed -i 's/^DISABLED_MODULES=""/DISABLED_MODULES="fglrx nv"/' \
	/root/etc/default/linux-restricted-modules-common

log_end_msg
