#! /bin/sh

PREREQ=""
DESCRIPTION="Adding APT-CDROM source..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

chroot /root apt-cdrom -m add
