#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling gdm guest session functionality..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

chroot /root dpkg -P gdm-guest-session || true

log_end_msg
