#! /bin/sh

PREREQ=""
DESCRIPTION="Enabling Plasma Netbook workspace if appropriate..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -e "/root/usr/share/autostart/plasma-netbook.desktop" ]; then
    sed -i "s,Hidden=true,," /root/usr/share/autostart/plasma-netbook.desktop
fi

log_end_msg
