#!/bin/sh

. /usr/share/debconf/confmodule
db_get passwd/username
username="$RET"

if [ -f /etc/gdm/gdm.conf ]; then
    # Configure GDM autologin

    sed -i \
        -e "s/^AutomaticLoginEnable=.*\$/AutomaticLoginEnable=true/" \
        -e "s/^AutomaticLogin=.*\$/AutomaticLogin=$username/" \
        -e "s/^TimedLoginEnable=.*\$/TimedLoginEnable=true/" \
        -e "s/^TimedLogin=.*\$/TimedLogin=$username/" \
        -e "s/^TimedLoginDelay=.*\$/TimedLoginDelay=10/" \
        /etc/gdm/gdm.conf
fi

if [ -f /etc/kde3/kdm/kdmrc ]; then
    # Configure KDM autologin
    sed -i -r \
        -e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
        -e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=$username/" \
        -e "s/^#?AutoReLogin=.*\$/AutoReLogin=true/" \
        /etc/kde3/kdm/kdmrc
fi

if which kpersonalizer >/dev/null; then
    # Disable first-login wizard for KDE
    if [ ! -f /etc/kde3/kpersonalizerrc ]; then
        cat > /etc/kde3/kpersonalizerrc <<EOF
[General]
FirstLogin=false
EOF
    else
        echo "I'm not smart enough to disable kpersonalizer startup" >&2
        echo "Because kpersonalizerrc already exists" >&2
    fi
fi

exit 0
