#!/bin/sh

if [ "$TERM_TYPE" = "serial" ]; then
    # Don't bother trying to configure or start X on a serial console
    rm -f /etc/rc?.d/S??[gxk]dm
    exit 0
fi

. /usr/share/debconf/confmodule

DEBUG_XORG_PACKAGE=yes \
    casper-reconfigure -fpassthrough xserver-xorg
