#!/bin/sh

gnome_screensaver_version=$(dpkg-query -W --showformat='${Version}' gnome-screensaver 2>/dev/null) || gnome_screensaver_version=""
if [ -n "$gnome_screensaver_version" ]; then
    gconftool-2 -t bool -s /apps/gnome-screensaver/lock false
fi
