#!/bin/sh

# XXX - Both of these hacks can be removed when the installer stops
# using devfs names

# This is needed because busybox init will look for the (devfs)
# console device before re-execing, and if it doesn't find it, it
# helpfully halts the system
cp -a /initrd/dev/vc /dev
cp -a /initrd/dev/tts /dev

# This is needed in order to eject the CD later (it was mounted using
# a devfs name)
cp -LR /initrd/dev/cdroms /root

exit 0
