#!/bin/sh

SAVEDIR=/var/log/casper

# Use the cdebconf confmodule, to get x_save
. /initrd/usr/share/debconf/confmodule
# Save the cdebconf database
db_x_save

test -d $SAVEDIR || mkdir -p $SAVEDIR

for log in /initrd/var/log/* /initrd/var/lib/cdebconf/questions.dat; do
    if [ -f "$log" ]; then
        gzip -9 < "$log" > $SAVEDIR/$(basename "$log").gz
    fi
done

exit 0
